export const SET_COUNTRIES = "SET_COUNTRIES";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
export const ORDER_COUNTRIES = "ORDER_COUNTRIES";
export const SET_EMAIL = "SET_EMAIL";
export const SET_ACCESS = "SET_ACCESS";
export  const DELETE_ACTIVITY="DELETE_ACTIVITY";
export const   UPDATE_ACTIVITY =" UPDATE_ACTIVITY";
export const RESET_FILTERED_COUNTRIES="RESET_FILTERED_COUNTRIES";